AppBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        creationDate:
            type: datetime
        lastUpdateDate:
            type: datetime
    manyToOne:
        author:
            targetEntity: AppBundle\Entity\Author
            inversedBy: posts
            cascade: [persist, remove]
    lifecycleCallbacks: {  }
